# Generated by Django 4.0.4 on 2022-10-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showstatic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveform',
            old_name='email',
            new_name='contactEmail',
        ),
        migrations.RenameField(
            model_name='saveform',
            old_name='message',
            new_name='contactMessage',
        ),
        migrations.RenameField(
            model_name='saveform',
            old_name='name',
            new_name='contactName',
        ),
        migrations.RenameField(
            model_name='saveform',
            old_name='subject',
            new_name='contactSubject',
        ),
    ]
