# Generated by Django 4.0.4 on 2022-10-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showstatic', '0002_rename_email_saveform_contactemail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='saveform',
            new_name='saveforms',
        ),
    ]
